var path = require('path');
const autoprefixer = require('autoprefixer');
var nodeExternals = require('webpack-node-externals');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {

	entry: path.resolve("routes.js"),
	output: {
		path:path.resolve("dist"),
		publicPath:"/",
		filename: "bundle.js",
		chunkFilename:"[name].[chunkhash].chunk.js"
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				loader: "babel-loader",
				exclude: /node_modules/,
				options: {
        	presets: ["es2015"]
				}
			},

			{
				test: /\.html$/,
				use: "html-loader",
			},
			{
    		test: /\.(jpeg|png|gif|svg|jpg)$/,
    		loader: "url-loader",
			},
			{
			 test: /\.css$/,
			 use: [ 'style-loader', 'css-loader' ]
		 }
		]
	},
	mode: "development",
	plugins:[new HtmlWebpackPlugin({
        inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
				template: path.join(process.cwd(), "index.html"),
      })]
};
